### ISSUE TITLE
IDE won't start up after cloning

### ISSUE THREAD

**Issue by Ubunfu** [Joespider/clide#16]
After cloning the repo and starting it up, it looks like a directory might be missing from an expected path?  Am I starting it up incorrectly?

**Reproduce:**
1. Clone repo into arbitrary directory
2. Run clide.sh with no arguments in a bash shell

**Result:**
```
ls: cannot access '/home/user/Programs/.clide/langs/': No such file or directory
ls: cannot access '/home/user/Programs/.clide/langs/': No such file or directory
./clide.sh: line 457: /home/user/Programs/.clide/lib/errorCode.sh: No such file or directory
```

**Comment by Wolverine-14** [comment]
It looks like clide isn't coping over/creating a folder correctly for fist time use or is pointing to the wrong location. for a temporary fix copy the langs folder from the cloned repository to the /home/user/Programs/.clide/ folder and clide should run then.

**Comment by Joespider** [comment]
Looks like its fixed now.
After adding these to the code, it should start up normally.

ShellPath=$(realpath $0)
root=$(dirname ${ShellPath})
...
ClideDir=${root}
